os: osx
language: objective-c
osx_image: xcode8.3
node_js: 5.1.1

before_install:
  - cd server

install:
  - npm install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - npm run build-server
  - npm run build-client
  - npm run test-local
